version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "modestengueyep1@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "modeste123"
    ports:
      - "80:8080"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:

