version: '3.1'
services:
  web:
    image: odoo:17.0
    container_name: odoo
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=db_momo
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo

  mydb:
    image: postgres:15
    container_name: db_momo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
