---
galaxy_info:
  author: Ngueyep modeste dolumin
  description: installation de l'application odoo
  company: eazytraining
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.9
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: CentOS
    versions:
    - all
  - name: RedHat
    versions: 
    - all 
  galaxy_tags:
    - docker
dependencies: []
