---
- hosts: 172.31.80.179
  become: true

  pre_tasks:
    # Install Docker
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    # Start and enable Docker
    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # Install docker-compose
    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

  roles:
    - role: odoo_role

- hosts:  172.31.84.97
  become: true
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/jenkins_key.pem
    ansible_user: ubuntu

  pre_tasks:
    # Install Docker
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    # Start and enable Docker
    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # Install docker-compose
    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

  roles:
    - role: pgadmin_role

- hosts: 172.31.92.218
  become: true
  vars:
    ansible_ssh_private_key_file: /home/ubuntu/jenkins_key.pem
    ansible_user: ubuntu

  vars_files:
    - vars/main.yml  

  roles:
    - role: vitrine_roles
