---
prod:
  hosts:
    172.31.46.53:
    172.31.36.253:
    172.31.42.221:

  vars:
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: /home/ubuntu/jenkins_key.pem
          ansible_user: ubuntu
